apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dashboard-loader
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dashboard-loader
  template:
    metadata:
      labels:
        app: grafana-dashboard-loader
    spec:
      serviceAccountName: grafana-dashboard-loader
      containers:
      - name: grafana-dashboard-loader
        image: clyang/grafana-dashboard-loader:latest